# Generated by Django 3.0.8 on 2022-11-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='команда')),
                ('group', models.CharField(default='A', max_length=1, verbose_name='группа')),
                ('flag', models.ImageField(blank=True, upload_to='', verbose_name='флаг')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время матча')),
                ('stage', models.CharField(choices=[('group', 'Групповой этап'), ('1/8', '1/8 финала'), ('1/4', 'Четвертьфинал'), ('1/2', 'Полуфинал'), ('final', 'Финал'), ('3rd', 'Матч за 3 место')], default='group', max_length=255, verbose_name='класс матча')),
                ('score_1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='голы команды 1')),
                ('score_2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='голы команды 2')),
                ('extra_score_1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='голы команды 1 в доп. время')),
                ('extra_score_2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='голы команды 2 в доп. время')),
                ('penalty_score_1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='голы команды 1 в серии пенальти')),
                ('penalty_score_2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='голы команды 2 в серии пенальти')),
                ('command_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_1', to='gambling.Command', verbose_name='команда 1')),
                ('command_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_2', to='gambling.Command', verbose_name='команда 2')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicevt', models.BooleanField(default=True, verbose_name='НИЦЭВТ')),
                ('money', models.BooleanField(default=False, verbose_name='Поставил деньги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_score_1', models.PositiveSmallIntegerField(verbose_name='голы команды 1')),
                ('guess_score_2', models.PositiveSmallIntegerField(verbose_name='голы команды 2')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='время прогноза')),
                ('guesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='угадывающий')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gambling.Match', verbose_name='матч')),
            ],
        ),
    ]
