databases:
  - name: world_champ_2022
    databaseName: world_champ_2022
    user: world_champ_2022

services:
  - type: web
    name: world_champ_2022
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: world_champ_2022
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
